### ISSUE TITLE
能否考虑加个openclash 谢谢

### ISSUE THREAD

**Issue by koriatan** [nantayo/N1-OpenWrt#2]
固件没有花里胡哨的东西，很稳定很好用。
只是使用发现passwall自动切换线路会有十几秒延迟。线路故障的时候，插件自动切换线路，有时正好在用，突然断网十几秒会影响比较大。
可不可以考虑加一个openclash，openclash配合规则自动切换线路是即时的，几乎无感。
谢谢

**Comment by nantayo** [comment]
你好,没有加openclash的原因是,大约半年前某次版本更新之后openclash在我所有不同架构的设备上莫名其妙的都不好用了,于是我就转投passwall了.
而且在低性能设备上openclash的表现会比passwall(ssr+)要差,因为它的详细分流更耗费性能.
关于你所说的,passwall(包括ssr+)的自动切换的确不好用,我更推荐你使用它旁边的"负载均衡"这个功能,为此我特意编译进去了最新的Haproxy.
这一功能的原理是让流量同时走多个你指定的节点,按照事先指定的权重和节点健康程度来分配具体每个节点走多少,因此不涉及到节点切换,除非节点全挂掉不然不会断网,我个人认为是一种比较好的解决方法.
YouTube上有一些视频是讲这个的,你可以先试一下好不好用.

**Comment by koriatan** [comment]
还有这种操作，我学会了，谢谢。
