### ISSUE TITLE
passwall tcp tup无法启用

### ISSUE THREAD

**Issue by xxiieang** [nantayo/N1-OpenWrt#3]
如题，DNS能启用，另外连个tcp tup 都无法启用

**Comment by nantayo** [comment]
你检查下“组件更新”里的“V2ray 版本”。正常应该是4.几或5.几，更新完后有几率版本号会变成和xray一样的1.5.几，这时候就会出错，你手动更新到最新版，再重启一下就可以了。

**Comment by nantayo** [comment]
我观察到一件事,目前v2ray最新的release为开发者预览版的5.0.2和5.0.1,它们存在莫名的未知bug.  
你可以在 https://github.com/v2fly/v2ray-core/releases/tag/v4.44.0 下载 v2ray-linux-arm64-v8a.zip  
解压后只需要里面名称为v2ray 的文件,然后用winscp一类的工具将N1的/usr/bin目录下的 v2ray 这个文件手动替换成上面的4.44.0,等过一段时间后再考虑更新到新版本.
