### ISSUE TITLE
tcp udp 未运行

### ISSUE THREAD

**Issue by asdffgdsf** [nantayo/N1-OpenWrt#4]
v2ray更新后,显示无，后来直接把v2ray节点名称改成xv2ray，TCP UDP显示运行，但是不稳定，无论旁路开DHCP 还是关 主开DHCP，国内国外都不稳定，最后把防火墙通信规则所有选项都关闭才安定了

**Comment by nantayo** [comment]
更新后显示无说明是有问题的,后续肯定是没法好好运作,有没有试过用U盘全新重刷?或者passwall恢复默认设置?

**Comment by asdffgdsf** [comment]
这个问题github好像很普遍，都是最近升级到5.02版本，都反映有这个问题，v2ray和xv2ray共用什么，不太懂，大佬下个版本能改进，恢复没用，vray和XRAY 一个版本1.5，更新后又显示无。

**Comment by nantayo** [comment]
> 这个问题github好像很普遍，都是最近升级到5.02版本，都反映有这个问题，v2ray和xv2ray共用什么，不太懂，大佬下个版本能改进，恢复没用，vray和XRAY 一个版本1.5，更新后又显示无。

你说得对,我尝试了一番,发现手动替换v2ray文件为5.0.1或者5.0.2均无法正常工作,而使用4.44.0则可以.  
你可以在【https://github.com/v2fly/v2ray-core/releases/tag/v4.44.0】下载【v2ray-linux-arm64-v8a.zip】.解压后只需要里面名称为【v2ray】的文件。  
然后用winscp一类的工具将N1的/usr/bin目录下的【v2ray】这个文件手动替换成上面的4.44.0,等过一段时间后再考虑更新到新版本.

**Comment by nantayo** [comment]
> 这个问题github好像很普遍，都是最近升级到5.02版本，都反映有这个问题，v2ray和xv2ray共用什么，不太懂，大佬下个版本能改进，恢复没用，vray和XRAY 一个版本1.5，更新后又显示无。

你说得对,我尝试了一番,发现手动替换v2ray文件为5.0.1或者5.0.2均无法正常工作,而使用4.44.0则可以.
你可以在"https://github.com/v2fly/v2ray-core/releases/tag/v4.44.0"下载"v2ray-linux-arm64-v8a.zip".解压后只需要里面名称为"v2ray"的文件。
然后用winscp一类的工具将N1的/usr/bin目录下的"v2ray"这个文件手动替换成上面的4.44.0,等过一段时间后再考虑更新到新版本.

**Comment by nantayo** [comment]
> 这个问题github好像很普遍，都是最近升级到5.02版本，都反映有这个问题，v2ray和xv2ray共用什么，不太懂，大佬下个版本能改进，恢复没用，vray和XRAY 一个版本1.5，更新后又显示无。

你说得对,我尝试了一番,发现手动替换v2ray文件为5.0.1或者5.0.2均无法正常工作,而使用4.44.0则可以.
你可以在  https://github.com/v2fly/v2ray-core/releases/tag/v4.44.0  下载  v2ray-linux-arm64-v8a.zip  解压后只需要里面名称为 
 v2ray  的文件。
然后用winscp一类的工具将N1的/usr/bin目录下的  v2ray  这个文件手动替换成上面的4.44.0,等过一段时间后再考虑更新到新版本.

**Comment by nantayo** [comment]
并且我发现5.0系列的v2ray内核文件目前仅仅是开发者预览版,并非稳定的发行版,因此它很可能存在各种意外的bug,我们先退回稳定版使用吧.

**Comment by asdffgdsf** [comment]
嗯，防火墙通信规则也有点问题，因为可能没用IPV6，所以索性全部关闭了，目前比较稳定

**Comment by nantayo** [comment]
> 嗯，防火墙通信规则也有点问题，因为可能没用IPV6，所以索性全部关闭了，目前比较稳定

目前我的防火墙除了删除了wan以外均为默认设置,自定义规则里有如下五条,我未作改动:  
iptables -t nat -I POSTROUTING -o eth0 -j MASQUERADE
iptables -t nat -A PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 53
iptables -t nat -A PREROUTING -p tcp --dport 53 -j REDIRECT --to-ports 53
[ -n "$(command -v ip6tables)" ] && ip6tables -t nat -A PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 53
[ -n "$(command -v ip6tables)" ] && ip6tables -t nat -A PREROUTING -p tcp --dport 53 -j REDIRECT --to-ports 53
一直稳定运行,你可以作为参考.

**Comment by asdffgdsf** [comment]
嗯，passwall 谷歌 和 GitHub 测试点我检测，都是2000ms, 节点都是200不到的，不知道哪里设置错了，但是网页打开速度也还可以

**Comment by nantayo** [comment]
> 嗯，passwall 谷歌 和 GitHub 测试点我检测，都是2000ms, 节点都是200不到的，不知道哪里设置错了，但是网页打开速度也还可以

按照我的经验,你可以尝试改动以下两处设置,或许有所帮助:  
1.基本设置-DNS,过滤模式选择"通过UDP节点请求DNS",远程DNS填写Google即可.当然你需要启用一个延迟相对低的UDP节点.根据我几次留意,UDP比TCP,以及Xray+DoH连接时间要少得多.
2.规则管理-规则版本,去除不需要的多余规则链接.这其中比较重要的是中国域名列表,默认的domains.china这个链接有6w+规则,超过ipset容量了,这经常导致问题.如果不用回国模式你可以换为apple.china这个链接,只有数百条规则.
