### ISSUE TITLE
passwall这版本有问题吗

### ISSUE THREAD

**Issue by asdffgdsf** [nantayo/N1-OpenWrt#5]
passwall这版本有问题吗  解析DNS，比如P站进去就找不到DNS，没法打开网页

**Comment by nantayo** [comment]
的确有问题，这几天测试了下passwall 4.45以及v2ray 5.0.x都有问题，可能是兼容性吧，具体的看readme开头的重要说明。

**Comment by asdffgdsf** [comment]
内核5.10.87更新 ，错误无法从服务器获得，如果完整更新系统，重启还是恢复成5.10.87版本

**Comment by nantayo** [comment]
你可以尝试将晶晨宝盒的插件设置里“OpenWrt 内核的下载路径”改成“https://github.com/breakings/OpenWrt/tree/main/opt/kernel“。
完整更新系统是从本项目的release下载，保持在5.10.87是正确的。
另外以N1的性能来说，我甚至觉得没必要再更新了，现在的内核早就能完全发挥了。

**Comment by asdffgdsf** [comment]
大佬，更新完后重启的确还是5 10 87版本，然后某些网址还是找不到DNS地址 现在正在诊断问题，打不开网页

**Comment by nantayo** [comment]
> 大佬，更新完后重启的确还是5 10 87版本，然后某些网址还是找不到DNS地址 现在正在诊断问题，打不开网页

#4 参考下这个。
我测试过，只要是4.44-1版本的passwall搭配4.44.0或以下版本的v2ray就都可以正常使用，openwrt的内核版本没有影响。
另外如果你改动了太多地方的话，最好恢复下passwall的出厂设置然后重新设置一遍，在地址栏输入http://192.168.3.101/cgi-bin/luci/admin/services/passwall/reset_config。

**Comment by asdffgdsf** [comment]
关了DNS 过滤器就能进了，过滤器里域名白名单加入网址也没法打开，后来索性关了DNS过滤器，也不知道如果开DNS过滤器，还要设置什么

**Comment by asdffgdsf** [comment]
解决了 过滤只开AG 和 AD

**Comment by nantayo** [comment]
我上午把xiaorouji的passwall源码fork过来回滚到4.44-1版本，编译出来的新固件就可以正常使用了，看来是最近的某些更新导致了问题，具体原因还暂时未知，可能是某些依赖的新版本存在兼容性问题。

**Comment by asdffgdsf** [comment]
怎么回滚4.44-1,看到passwall版本已经更新到4.45了,解析是有点问题

**Comment by nantayo** [comment]
> 怎么回滚4.44-1,看到passwall版本已经更新到4.45了,解析是有点问题

下载release里的那个固件，我已经fork过来把有问题的改动修好了编译进去了。

**Comment by asdffgdsf** [comment]
这下好了，v2ray 改成4.44都没用了，tcp udp都是未运行状态

**Comment by nantayo** [comment]
> 这下好了，v2ray 改成4.44都没用了，tcp udp都是未运行状态

那你得检查下设置有没有问题了，我测试过正常使用。

**Comment by asdffgdsf** [comment]
刷进去，看到passwall版本已经变成4.46-2，比4.45还新啊，v2和xray版本都是4.44

**Comment by nantayo** [comment]
> 刷进去，看到passwall版本已经变成4.46-2，比4.45还新啊，v2和xray版本都是4.44

readme开头就写了之前bug的原因，是新版删掉了一个参数，加回来就好了，至于版本应该是V2 4.44，Xray 1.5.2。
而且我更建议直接把V2的文件删了，这样订阅V2机场会直接用Xray，比V2好用多了……
